version: 1.1.{build}
image:
- Visual Studio 2017
branches:
  only:
  - master
configuration: Release
platform:
- Win32
- x64
matrix:
  fast_finish: true
init:
- ps: 
install:
- ps: >-
    md -Path "..\Objectively"

    Push-Location "..\Objectively\"

    [Environment]::CurrentDirectory = $PWD

    (New-Object System.Net.WebClient).DownloadFile("https://ci.appveyor.com/api/projects/Paril/objectively/artifacts/__dep.zip?job=Platform%3A+" + $env:PLATFORM, "tmp.zip")

    7z x tmp.zip -aos "*"

    Remove-Item "tmp.*"

    Pop-Location

    [Environment]::CurrentDirectory = $PWD
build:
  parallel: true
  verbosity: minimal
  project: ObjectivelyMVC.vs15\ObjectivelyMVC.sln
after_build:
- ps: >-
    7z a __dep.zip -r *.h

    7z a __dep.zip -r *.lib

    7z a __dep.zip -r *.dll

    7z a __dep.zip -r *.pdb
test: off
deploy: off
artifacts:
- path: __dep.zip
on_success:
- ps: >-
    $token = $env:API_TOKEN

    $headers = @{ "Authorization" = "Bearer $token"}

    $body = @{accountName = $env:API_NAME; projectSlug = "quetoo"}

    $bodyAsJson = $body | ConvertTo-json

    if ($env:Platform -Match "x64") {

    Invoke-Restmethod -uri 'https://ci.appveyor.com/api/builds' -Headers $headers -Method Post -Body $bodyAsjson -ContentType "application/json"

    }